actions:
    port: 8000
chain:
    bech32_prefix: bridge
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - feegrant
        - gov
        - mint
        - slashing
        - staking
        - distribution
        - actions
        - upgrade
        - nft
database:
    host: scan-pg
    max_idle_connections: 10
    max_open_connections: 20
    name: scan
    partition_batch: 1000
    partition_size: 100000
    password: scan
    port: 5432
    url:
    user: scan
logging:
    format: text
    level: debug
node:
    config:
        grpc:
            address:  http://localhost:9090
            insecure: true
        rpc:
            address: http://localhost:26657
            client_name: juno
            max_connections: 10
    type: remote
parsing:
    average_block_time: 5s
    genesis_file_path: genesis.json
    listen_new_blocks: true
    parse_genesis: false
    parse_old_blocks: false
    start_height: 1
    workers: 1