FROM golang:1.23-alpine AS builder

RUN apk update && apk add --no-cache make git
WORKDIR /go/src/github.com/forbole/callisto
COPY vendor .
COPY . .

RUN apk add build-base

ENV GO111MODULE="on"
ENV CGO_ENABLED=1
ENV GOOS="linux"

RUN go build -mod=vendor -o /usr/local/bin/bdjuno /go/src/github.com/forbole/callisto/cmd/bdjuno

FROM alpine:latest
COPY --from=builder /usr/local/bin/bdjuno /usr/local/bin/bdjuno
RUN apk add --no-cache ca-certificates
CMD [ "bdjuno" ]