// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/genesis.proto

package v24

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	Params                  Params                   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Chains                  []Chain                  `protobuf:"bytes,2,rep,name=chains,proto3" json:"chains"`
	Tokens                  []Token                  `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens"`
	Transactions            []Transaction            `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions"`
	TransactionsSubmissions []TransactionSubmissions `protobuf:"bytes,5,rep,name=transactions_submissions,json=transactionsSubmissions,proto3" json:"transactions_submissions"`
	Referrals               []Referral               `protobuf:"bytes,6,rep,name=referrals,proto3" json:"referrals"`
	ReferralsRewards        []ReferralRewards        `protobuf:"bytes,7,rep,name=referralsRewards,proto3" json:"referralsRewards"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fdd574b337deec5, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetChains() []Chain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *GenesisState) GetTokens() []Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *GenesisState) GetTransactions() []Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *GenesisState) GetTransactionsSubmissions() []TransactionSubmissions {
	if m != nil {
		return m.TransactionsSubmissions
	}
	return nil
}

func (m *GenesisState) GetReferrals() []Referral {
	if m != nil {
		return m.Referrals
	}
	return nil
}

func (m *GenesisState) GetReferralsRewards() []ReferralRewards {
	if m != nil {
		return m.ReferralsRewards
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "core.bridge.GenesisState")
}

func init() { proto.RegisterFile("bridge/genesis.proto", fileDescriptor_9fdd574b337deec5) }

var fileDescriptor_9fdd574b337deec5 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0x6f, 0xe2, 0x30,
	0x18, 0xc6, 0x93, 0x83, 0xcb, 0xe9, 0x0c, 0xc3, 0xc9, 0x70, 0x3a, 0x1f, 0x6a, 0x03, 0x6a, 0x17,
	0x96, 0xc6, 0x85, 0x4e, 0xdd, 0xaa, 0x74, 0xe8, 0x56, 0x21, 0xe8, 0xc4, 0x52, 0x39, 0x89, 0x1b,
	0xd2, 0x12, 0x8c, 0x6c, 0xd3, 0x3f, 0xdf, 0xa2, 0x1f, 0x8b, 0x91, 0xb1, 0xea, 0x50, 0x55, 0xf0,
	0x45, 0xaa, 0x38, 0x0e, 0x49, 0x5a, 0xba, 0xe1, 0xf7, 0x79, 0x7e, 0x3f, 0xfb, 0x45, 0x01, 0x4d,
	0x8f, 0x47, 0x41, 0x48, 0x71, 0x48, 0x67, 0x54, 0x44, 0xc2, 0x99, 0x73, 0x26, 0x19, 0xac, 0xf9,
	0x8c, 0x53, 0x27, 0x8d, 0x5a, 0xcd, 0x90, 0x85, 0x4c, 0xcd, 0x71, 0xf2, 0x2b, 0xad, 0xb4, 0x1a,
	0x1a, 0x9c, 0x13, 0x4e, 0x62, 0xcd, 0xb5, 0xfe, 0xeb, 0x61, 0xcc, 0x02, 0x3a, 0x15, 0x58, 0xb2,
	0x3b, 0x3a, 0xdb, 0x1d, 0xf9, 0x13, 0x12, 0x65, 0x51, 0xfb, 0x13, 0xc5, 0xc9, 0x4c, 0x10, 0x5f,
	0x46, 0x2c, 0x2b, 0xec, 0x97, 0x0b, 0x9c, 0xde, 0x50, 0xce, 0xc9, 0x54, 0xdf, 0x7a, 0xf0, 0x5a,
	0x01, 0xf5, 0x8b, 0xf4, 0xfd, 0x23, 0x49, 0x24, 0x85, 0x3d, 0x60, 0xa5, 0xcf, 0x42, 0x66, 0xc7,
	0xec, 0xd6, 0xfa, 0x0d, 0xa7, 0xb0, 0x8f, 0x33, 0x50, 0x91, 0x5b, 0x5d, 0xbe, 0xb5, 0x8d, 0xa1,
	0x2e, 0xc2, 0x63, 0x60, 0xa9, 0x27, 0x09, 0xf4, 0xa3, 0x53, 0xe9, 0xd6, 0xfa, 0xb0, 0x84, 0x9c,
	0x27, 0x51, 0x46, 0xa4, 0xbd, 0x84, 0x50, 0xfb, 0x09, 0x54, 0xd9, 0x41, 0x5c, 0x25, 0x51, 0x46,
	0xa4, 0x3d, 0xe8, 0x82, 0x7a, 0x61, 0x37, 0x81, 0xaa, 0x8a, 0x43, 0x65, 0x2e, 0x2f, 0x68, 0xba,
	0xc4, 0xc0, 0x00, 0xa0, 0xe2, 0xf9, 0x5a, 0x2c, 0xbc, 0x38, 0x12, 0x42, 0xf9, 0x7e, 0x2a, 0xdf,
	0xe1, 0x77, 0xbe, 0x51, 0x5e, 0xd5, 0xea, 0x7f, 0x45, 0x55, 0x21, 0x86, 0xa7, 0xe0, 0xf7, 0xf6,
	0x4f, 0x46, 0x96, 0xd2, 0xfe, 0x2d, 0x69, 0x87, 0x3a, 0xd5, 0xa2, 0xbc, 0x0d, 0x2f, 0xc1, 0x9f,
	0xed, 0x61, 0x48, 0x1f, 0x08, 0x0f, 0x04, 0xfa, 0xa5, 0x0c, 0x7b, 0x3b, 0x0d, 0xba, 0xa3, 0x45,
	0x5f, 0x58, 0x77, 0xbc, 0x5c, 0xdb, 0xe6, 0x6a, 0x6d, 0x9b, 0xef, 0x6b, 0xdb, 0x7c, 0xde, 0xd8,
	0xc6, 0x6a, 0x63, 0x1b, 0x2f, 0x1b, 0xdb, 0x18, 0x9f, 0x85, 0x91, 0x9c, 0x2c, 0x3c, 0xc7, 0x67,
	0x31, 0x76, 0x95, 0x74, 0x4a, 0x85, 0x38, 0x1a, 0x70, 0x76, 0x4b, 0x7d, 0x89, 0xbd, 0x7c, 0x94,
	0xdc, 0x8b, 0xef, 0x7b, 0x7d, 0xfc, 0xa8, 0xa7, 0x58, 0x3e, 0xcd, 0xa9, 0xf0, 0x2c, 0xf5, 0xfd,
	0x9c, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x45, 0x33, 0xd5, 0x05, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReferralsRewards) > 0 {
		for iNdEx := len(m.ReferralsRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReferralsRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Referrals) > 0 {
		for iNdEx := len(m.Referrals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Referrals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TransactionsSubmissions) > 0 {
		for iNdEx := len(m.TransactionsSubmissions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TransactionsSubmissions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Transactions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Chains) > 0 {
		for _, e := range m.Chains {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Transactions) > 0 {
		for _, e := range m.Transactions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TransactionsSubmissions) > 0 {
		for _, e := range m.TransactionsSubmissions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Referrals) > 0 {
		for _, e := range m.Referrals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ReferralsRewards) > 0 {
		for _, e := range m.ReferralsRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, Chain{})
			if err := m.Chains[len(m.Chains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, Token{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, Transaction{})
			if err := m.Transactions[len(m.Transactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionsSubmissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionsSubmissions = append(m.TransactionsSubmissions, TransactionSubmissions{})
			if err := m.TransactionsSubmissions[len(m.TransactionsSubmissions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrals = append(m.Referrals, Referral{})
			if err := m.Referrals[len(m.Referrals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralsRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferralsRewards = append(m.ReferralsRewards, ReferralRewards{})
			if err := m.ReferralsRewards[len(m.ReferralsRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
