// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/models/chain.proto

package v21

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainType int32

const (
	ChainType_EVM     ChainType = 0
	ChainType_BITCOIN ChainType = 1
	ChainType_COSMOS  ChainType = 2
	ChainType_OTHER   ChainType = 3
	ChainType_ZANO    ChainType = 4
	ChainType_TON     ChainType = 5
	ChainType_SOLANA  ChainType = 6
)

var ChainType_name = map[int32]string{
	0: "EVM",
	1: "BITCOIN",
	2: "COSMOS",
	3: "OTHER",
	4: "ZANO",
	5: "TON",
	6: "SOLANA",
}

var ChainType_value = map[string]int32{
	"EVM":     0,
	"BITCOIN": 1,
	"COSMOS":  2,
	"OTHER":   3,
	"ZANO":    4,
	"TON":     5,
	"SOLANA":  6,
}

func (x ChainType) String() string {
	return proto.EnumName(ChainType_name, int32(x))
}

func (ChainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ec0e281693ee2200, []int{0}
}

type Chain struct {
	Id   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type ChainType `protobuf:"varint,2,opt,name=type,proto3,enum=core.bridge.v21.ChainType" json:"type,omitempty"`
	// bridge_address is the address of the bridge contract on the chain
	BridgeAddress string `protobuf:"bytes,3,opt,name=bridge_address,json=bridgeAddress,proto3" json:"bridge_address,omitempty"`
	// operator is the address of the operator of the bridge contract
	Operator      string `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Confirmations uint32 `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Name          string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec0e281693ee2200, []int{0}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return m.Size()
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Chain) GetType() ChainType {
	if m != nil {
		return m.Type
	}
	return ChainType_EVM
}

func (m *Chain) GetBridgeAddress() string {
	if m != nil {
		return m.BridgeAddress
	}
	return ""
}

func (m *Chain) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Chain) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Chain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("core.bridge.v21.ChainType", ChainType_name, ChainType_value)
	proto.RegisterType((*Chain)(nil), "core.bridge.v21.Chain")
}

func init() { proto.RegisterFile("bridge/models/chain.proto", fileDescriptor_ec0e281693ee2200) }

var fileDescriptor_ec0e281693ee2200 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x6d, 0xda, 0xdd, 0x8e, 0xb4, 0x86, 0xc1, 0x8b, 0x6c, 0x90, 0x50, 0x44, 0xa1,
	0x2c, 0x98, 0xa1, 0xf5, 0x05, 0x6c, 0xcb, 0x82, 0x0b, 0x6e, 0x23, 0x69, 0x50, 0xe8, 0x8d, 0x4c,
	0x92, 0xd9, 0xec, 0x48, 0x93, 0x13, 0x67, 0xa6, 0xc5, 0xbc, 0x85, 0x0f, 0xe5, 0x85, 0x97, 0x7b,
	0xe9, 0xa5, 0xb4, 0x2f, 0x22, 0x99, 0x84, 0x8a, 0xde, 0x9d, 0x7c, 0xff, 0x7f, 0x7e, 0xfe, 0x9c,
	0xc1, 0x57, 0xb1, 0x14, 0x69, 0xc6, 0x69, 0x0e, 0x29, 0xdf, 0x29, 0x9a, 0x3c, 0x30, 0x51, 0xf8,
	0xa5, 0x04, 0x0d, 0xe4, 0x69, 0x02, 0x92, 0xfb, 0x8d, 0xee, 0x1f, 0xe6, 0x33, 0xf7, 0x2a, 0x03,
	0xc8, 0x76, 0x9c, 0x1a, 0x39, 0xde, 0xdf, 0x53, 0x56, 0x54, 0x8d, 0xd7, 0xbd, 0x4e, 0x40, 0xe5,
	0xa0, 0x68, 0xcc, 0x14, 0xa7, 0x5f, 0xf7, 0x5c, 0x56, 0xf4, 0x30, 0x8b, 0xb9, 0x66, 0x33, 0x5a,
	0xb2, 0x4c, 0x14, 0x4c, 0x0b, 0x68, 0x73, 0xdd, 0xe7, 0x6d, 0x0c, 0x2b, 0x05, 0x65, 0x45, 0x01,
	0xda, 0x88, 0xaa, 0x55, 0x9f, 0x65, 0x90, 0x81, 0x19, 0x69, 0x3d, 0x35, 0xf4, 0xc5, 0x0f, 0x84,
	0xfb, 0xab, 0xba, 0x1b, 0x19, 0xe3, 0xae, 0x48, 0x1d, 0x34, 0x41, 0xd3, 0x61, 0xd8, 0x15, 0x29,
	0xf1, 0xb1, 0xa5, 0xab, 0x92, 0x3b, 0xdd, 0x09, 0x9a, 0x8e, 0xe7, 0xae, 0xff, 0x5f, 0x69, 0xdf,
	0x6c, 0x45, 0x55, 0xc9, 0x43, 0xe3, 0x23, 0xaf, 0xf0, 0xb8, 0x51, 0x3f, 0xb3, 0x34, 0x95, 0x5c,
	0x29, 0xa7, 0x67, 0xb2, 0x46, 0x0d, 0x5d, 0x34, 0x90, 0xb8, 0xf8, 0x12, 0x4a, 0x2e, 0x99, 0x06,
	0xe9, 0x58, 0xc6, 0x70, 0xfe, 0x26, 0x2f, 0xf1, 0x28, 0x81, 0xe2, 0x5e, 0xc8, 0xbc, 0x69, 0xee,
	0xf4, 0x27, 0x68, 0x3a, 0x0a, 0xff, 0x85, 0x84, 0x60, 0xab, 0x60, 0x39, 0x77, 0x06, 0x66, 0xdb,
	0xcc, 0xd7, 0x9f, 0xf0, 0xf0, 0xdc, 0x87, 0x5c, 0xe0, 0xde, 0xcd, 0xc7, 0x3b, 0xbb, 0x43, 0x9e,
	0xe0, 0x8b, 0xe5, 0x6d, 0xb4, 0x0a, 0x6e, 0xd7, 0x36, 0x22, 0x18, 0x0f, 0x56, 0xc1, 0xe6, 0x2e,
	0xd8, 0xd8, 0x5d, 0x32, 0xc4, 0xfd, 0x20, 0x7a, 0x77, 0x13, 0xda, 0x3d, 0x72, 0x89, 0xad, 0xed,
	0x62, 0x1d, 0xd8, 0x56, 0xbd, 0x16, 0x05, 0x6b, 0xbb, 0x5f, 0x3b, 0x37, 0xc1, 0xfb, 0xc5, 0x7a,
	0x61, 0x0f, 0x96, 0xdb, 0x9f, 0x47, 0x0f, 0x3d, 0x1e, 0x3d, 0xf4, 0xfb, 0xe8, 0xa1, 0xef, 0x27,
	0xaf, 0xf3, 0x78, 0xf2, 0x3a, 0xbf, 0x4e, 0x5e, 0x67, 0xfb, 0x36, 0x13, 0xfa, 0x61, 0x1f, 0xfb,
	0x09, 0xe4, 0x74, 0x69, 0x7e, 0x71, 0xc7, 0x95, 0x7a, 0xfd, 0x41, 0xc2, 0x17, 0x9e, 0x68, 0x1a,
	0xff, 0x45, 0xf5, 0xe5, 0xe8, 0x61, 0x36, 0xa7, 0xdf, 0x5a, 0x4a, 0xeb, 0x83, 0xa9, 0x78, 0x60,
	0x9e, 0xe0, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0xb4, 0x2a, 0x7b, 0x2b, 0x02, 0x00,
	0x00,
}

func (m *Chain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x32
	}
	if m.Confirmations != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Confirmations))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BridgeAddress) > 0 {
		i -= len(m.BridgeAddress)
		copy(dAtA[i:], m.BridgeAddress)
		i = encodeVarintChain(dAtA, i, uint64(len(m.BridgeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Chain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovChain(uint64(m.Type))
	}
	l = len(m.BridgeAddress)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.Confirmations != 0 {
		n += 1 + sovChain(uint64(m.Confirmations))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func sovChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChain(x uint64) (n int) {
	return sovChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Chain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confirmations", wireType)
			}
			m.Confirmations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Confirmations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChain = fmt.Errorf("proto: unexpected end of group")
)
